### ISSUE TITLE
Question about scope

### ISSUE THREAD

**Issue by barbhackk** [dwgebler/OAuth2ServerDemo#3]
Hi Dave,
Many thanks for this tutorial. It also allowed me to better understand how OAuth 2 works.

I do, however, have a question. In the case where I have a minimum scope for each customer (email) and additional scopes available (email, profile, preference). When I create a new client, the latter will have the minimum scope 'email'.

Now, I want to call '/authorize' with scope="email profile". “profile” is not defined for the client but it is part of the scopes available.

I would then like the user to see the email and profile scope on the consent page and accept.

I therefore save the scopes for this user (i.e. "email + profile") in the database except that when redirecting to '/authorize' with the all dataset request, I have an 

> [!CAUTION]
OAuth failure: Error : invalid_scope, Description: The requested scope is invalid, unknown, or malformed**

Indeed the scope is not specified for this client (oauth_client table)...

Should I specify ALL possible scopes for this client?

What I would like is scope=null the user will have the minimum 'email' scope... and if I add other available scopes, the consent page will redisplay with the new scopes...

Thk for your help.

**Comment by dwgebler** [comment]
Yes you would need to have the scopes defined for the client for the authorization endpoint to work without error. I wouldn't recommend an approach where you consider `null` to be any scope; permissions associated with a profile and token in OAuth2 or any sort of IDAM system should be explicit at all times.

**Comment by barbhackk** [comment]
Hi, thks for your reply.

In Github, for exemple, it's possible to get new access token with no "scope" parameter `scope=''`. Github present a consent page with only one default grant access... email and other lambda profil information.

If I get a new access token with a `scope='repo'`, Github present a consent page with the new requested grant access.

In your tutorial, I modify the consent page with test if scope is isset. If not, i force scope with minimal value and `$request->query->set('scope', 'min_scope')` and merge with the existing consent user scope.

On the other hand, in my config, I set all scope for this client... can potentially request another scope. It's not a problem because I have a consent page to test requested scope.

I think I have a good approch to get similar than Github ? The client have all available scope and the consent page show the requested scope that the user can validate or not.

**Sorry i'm french guy and my english is possible bad ;)**

**Comment by dwgebler** [comment]
I don't recommend this approach, personally. I'm not saying it isn't workable/feasible to do, but I think you should always be explicit about scopes in the process. What GitHub does isn't necessarily the best model.

**Comment by barbhackk** [comment]
> I don't recommend this approach, personally. I'm not saying it isn't workable/feasible to do, but I think you should always be explicit about scopes in the process. What GitHub does isn't necessarily the best model.

Thanks for all. 
Indeed my approach is not recommended ;)
