### ISSUE TITLE
Insert oauth2_client in BootstrapCommand

### ISSUE THREAD

**Issue by davidnectarestudio** [dwgebler/OAuth2ServerDemo#4]
It is possible to insert an `oauth2_client` entity with Doctrine methods instead of with a 'direct' connection?

**Comment by dwgebler** [comment]
@davidnectarestudio probably, but why? Are you having trouble running the tutorial code?

**Comment by davidnectarestudio** [comment]
Thanks for your answer @dwgebler 

My doubt it was related with why to write a direct SQL insert statement if we previously have defined a related entity and can be used in the command to make the insert like a common Doctrine persist method.
